### ISSUE TITLE
Configuración de Travis

### ISSUE THREAD

**Issue by bustamante-jt** [JulietaCaceres/TPDragonBall#1]
Falta activar el repositorio en Travis y corregir el archivo yml:
```
language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
```
Acá está la documentación del formato: https://docs.travis-ci.com/user/languages/java/
